### ISSUE TITLE
validate_certs: no missing for some of the images

### ISSUE THREAD

**Issue by markdryan** [clearlinux/ansible-role-ciao-controller#1]
validate_certs:no is specified for some images but not others.  In particular it is missing from the redhat and the cnci_image.  The role failed when run from behind a proxy without this variable set.

**Comment by albertomurillo** [comment]
issues are tracked in github.com/clearlinux/clear-config-management
There is an issue there to add a disclaimer on each role README.md file this info

**Comment by markdryan** [comment]
@albertomurillo Are you going to migrate these bugs over?
